### ISSUE TITLE
ERROR after install

### ISSUE THREAD

**Issue by duderino999** [Chinilla/chinilla-blockchain#57]
### Discussed in https://github.com/Chinilla/chinilla-blockchain/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **duderino999** April  4, 2022</sup>
Hi there,

after installing and trying to start the FULL NODE, I am getting below error message:

(venv) farmer@chiaforks:~/forks/chinilla-blockchain$ chinilla start node -r
Daemon not started yet
Starting daemon
chinilla_full_node: started
(venv) farmer@chiaforks:~/forks/chinilla-blockchain$ Traceback (most recent call last):
  File "/home/farmer/forks/chinilla-blockchain/venv/bin/chinilla_full_node", line 33, in <module>
    sys.exit(load_entry_point('chinilla-blockchain', 'console_scripts', 'chinilla_full_node')())
  File "/home/farmer/forks/chinilla-blockchain/venv/bin/chinilla_full_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/farmer/forks/chinilla-blockchain/chinilla/server/start_full_node.py", line 8, in <module>
    from chinilla.full_node.full_node import FullNode
  File "/home/farmer/forks/chinilla-blockchain/chinilla/full_node/full_node.py", line 34, in <module>
    from chinilla.full_node.mempool_manager import MempoolManager
  File "/home/farmer/forks/chinilla-blockchain/chinilla/full_node/mempool_manager.py", line 9, in <module>
    from chia.util.inline_executor import InlineExecutor
ModuleNotFoundError: No module named 'chia'

Any idea?

Cheers</div>

**Comment by duderino999** [comment]
OK, I fixed it myself. Forgot to git clone with -b latest --recurse-submodules
